### ISSUE TITLE
Generate pre-filled Supply crates

### ISSUE THREAD

**Issue by Tapawingo** [clustermod/CMF3#20]
**Generate pre-filled Supply crates:**
Generate supply crates based on kosher arsenal loadout. Also generate names for the suply crates ([#19](https://github.com/clustermod/CMF3/issues/19))

**Comment by PervonHarke** [comment]
Request to also have this feature for vehicles.

**Comment by Tapawingo** [comment]
@PervonHarke 
I won't implement that, at least not anytime soon. I prefer crates over vehicles since they can very quickly be moved between vehicles if needed.

**Comment by Tapawingo** [comment]
Added in v2.1.0.53
