### ISSUE TITLE
Logistics - Logistic and Vehicle Spawner button in CMF 3DEN submenu

### ISSUE THREAD

**Issue by PervonHarke** [clustermod/CMF3#24]
**Description of feature:**
In the 3DEN CMF toolbar menu where the "Toggle koscherArsenal AmmoBox" button is placed the following buttons would be useful:
- Toggle koscherGarage
- Toggle koscherLogistics

They could be placed different and not next to the koscherArsenal button but they both would make a good fit in that toolbar menu.

**Comment by Tapawingo** [comment]
They are planned to be added in the future. generally, any function that requires a object will get a button in the CMF entity menu for greater accessability.

**Comment by Tapawingo** [comment]
Duplicate of https://github.com/clustermod/CMF3/issues/32 (even tho urs came first :). I recommend you follow the other issue for updates).
